name: keep
channels:
  - intel
  - defaults
dependencies:
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - impi_rt=2019.8
  - intelpython=2020.2
  - mpi4py=3.0.3
  - openssl=1.1.1h
  - pip=20.2.2
  - python=3.7.7
  - setuptools=49.6.0
  - sqlite=3.32.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.35.1
  - wincertstore=0.2
  - pip:
    - absl-py==0.10.0
    - alembic==1.4.3
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - atari-py==0.2.6
    - attrs==20.1.0
    - backcall==0.2.0
    - base58==2.0.1
    - bitarray==1.2.2
    - bleach==3.1.5
    - cachetools==4.1.1
    - cffi==1.14.2
    - chardet==3.0.4
    - cliff==3.4.0
    - cloudpickle==1.6.0
    - cmaes==0.6.1
    - cmd2==1.3.10
    - colorama==0.4.3
    - colorlog==4.2.1
    - cycler==0.10.0
    - cython==0.29.21
    - cytoolz==0.11.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.2
    - entrypoints==0.3
    - eth-abi==2.1.1
    - eth-account==0.5.3
    - eth-hash==0.2.0
    - eth-keyfile==0.5.1
    - eth-keys==0.3.3
    - eth-rlp==0.2.0
    - eth-typing==2.2.2
    - eth-utils==1.9.5
    - future==0.18.2
    - gast==0.2.2
    - google-auth==1.21.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - grpcio==1.31.0
    - gym==0.17.3
    - h5py==2.10.0
    - hexbytes==0.2.1
    - idna==2.10
    - importlib-metadata==1.7.0
    - ipfshttpclient==0.6.1
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.16.0
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab==2.2.6
    - jupyterlab-server==1.2.0
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lru-dict==1.1.6
    - mako==1.1.3
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.3.1
    - mistune==0.8.4
    - multiaddr==0.0.9
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - netaddr==0.8.0
    - notebook==6.1.3
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opencv-python==4.4.0.44
    - opt-einsum==3.3.0
    - optuna==0.16.0
    - packaging==20.4
    - pandas==1.1.1
    - pandocfilters==1.4.2
    - parsimonious==0.8.1
    - parso==0.7.1
    - pbr==5.5.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prettytable==0.7.2
    - prometheus-client==0.8.0
    - promise==2.3
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - psycopg2==2.8.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pycryptodome==3.9.8
    - pyglet==1.5.0
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyperclip==1.8.0
    - pypiwin32==223
    - pyreadline==2.1
    - pyrsistent==0.16.0
    - pytelegrambotapi==3.7.3
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytz==2020.1
    - pywin32==228
    - pywinpty==0.5.7
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rlp==2.0.0a1
    - rsa==4.6
    - rusty-rlp==0.1.15
    - scikit-learn==0.23.2
    - scipy==1.4.0
    - seaborn==0.10.1
    - send2trash==1.5.0
    - sklearn==0.0
    - sqlalchemy==1.3.19
    - stable-baselines==2.10.1
    - stevedore==3.2.2
    - tensorboard==1.15.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==1.15.0
    - tensorflow-datasets==3.2.1
    - tensorflow-estimator==1.15.1
    - tensorflow-metadata==0.24.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - toolz==0.11.1
    - tornado==6.0.4
    - tqdm==4.50.0
    - traitlets==4.3.3
    - typing==3.7.4.3
    - typing-extensions==3.7.4.3
    - uniswap-python==0.4.4
    - urllib3==1.25.10
    - varint==1.0.2
    - wcwidth==0.2.5
    - web3==5.12.1
    - webencodings==0.5.1
    - websockets==8.1
    - werkzeug==1.0.1
    - zipp==3.1.0

